/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrandPresetsRouteImport } from './routes/brand-presets'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsIdReviewRouteImport } from './routes/campaigns.$id.review'
import { Route as CampaignsIdExportRouteImport } from './routes/campaigns.$id.export'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPresetsRoute = BrandPresetsRouteImport.update({
  id: '/brand-presets',
  path: '/brand-presets',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdReviewRoute = CampaignsIdReviewRouteImport.update({
  id: '/campaigns/$id/review',
  path: '/campaigns/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdExportRoute = CampaignsIdExportRouteImport.update({
  id: '/campaigns/$id/export',
  path: '/campaigns/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-presets': typeof BrandPresetsRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/campaigns/$id/export': typeof CampaignsIdExportRoute
  '/campaigns/$id/review': typeof CampaignsIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-presets': typeof BrandPresetsRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/campaigns/$id/export': typeof CampaignsIdExportRoute
  '/campaigns/$id/review': typeof CampaignsIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-presets': typeof BrandPresetsRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/campaigns/$id/export': typeof CampaignsIdExportRoute
  '/campaigns/$id/review': typeof CampaignsIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/brand-presets'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/campaigns/new'
    | '/campaigns/'
    | '/campaigns/$id/export'
    | '/campaigns/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/brand-presets'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/campaigns/new'
    | '/campaigns'
    | '/campaigns/$id/export'
    | '/campaigns/$id/review'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/brand-presets'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/campaigns/new'
    | '/campaigns/'
    | '/campaigns/$id/export'
    | '/campaigns/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BrandPresetsRoute: typeof BrandPresetsRoute
  DashboardRoute: typeof DashboardRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CampaignsIdExportRoute: typeof CampaignsIdExportRoute
  CampaignsIdReviewRoute: typeof CampaignsIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-presets': {
      id: '/brand-presets'
      path: '/brand-presets'
      fullPath: '/brand-presets'
      preLoaderRoute: typeof BrandPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/review': {
      id: '/campaigns/$id/review'
      path: '/campaigns/$id/review'
      fullPath: '/campaigns/$id/review'
      preLoaderRoute: typeof CampaignsIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/export': {
      id: '/campaigns/$id/export'
      path: '/campaigns/$id/export'
      fullPath: '/campaigns/$id/export'
      preLoaderRoute: typeof CampaignsIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BrandPresetsRoute: BrandPresetsRoute,
  DashboardRoute: DashboardRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CampaignsIdExportRoute: CampaignsIdExportRoute,
  CampaignsIdReviewRoute: CampaignsIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
